version: "3"
services:
  app:
    build: .

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:12.9

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
